import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Viewport } from 'next';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export const viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1,
};
 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montSerrat.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
